config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  resources :hardwares
  resources :exploatations

end

app/models/exploatation.rb
class Exploatation < ActiveRecord::Base
end

app/models/hardware.rb
class Hardware < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exploatations_controller.rb
class ExploatationsController < ApplicationController
  before_action :set_exploatation, only: [:show, :edit, :update, :destroy]

  # GET /exploatations
  # GET /exploatations.json
  def index
    @exploatations = Exploatation.all
  end

  # GET /exploatations/1
  # GET /exploatations/1.json
  def show
  end

  # GET /exploatations/new
  def new
    @exploatation = Exploatation.new
  end

  # GET /exploatations/1/edit
  def edit
  end

  # POST /exploatations
  # POST /exploatations.json
  def create
    @exploatation = Exploatation.new(exploatation_params)

    respond_to do |format|
      if @exploatation.save
        format.html { redirect_to @exploatation, notice: 'Exploatation was successfully created.' }
        format.json { render :show, status: :created, location: @exploatation }
      else
        format.html { render :new }
        format.json { render json: @exploatation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exploatations/1
  # PATCH/PUT /exploatations/1.json
  def update
    respond_to do |format|
      if @exploatation.update(exploatation_params)
        format.html { redirect_to @exploatation, notice: 'Exploatation was successfully updated.' }
        format.json { render :show, status: :ok, location: @exploatation }
      else
        format.html { render :edit }
        format.json { render json: @exploatation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exploatations/1
  # DELETE /exploatations/1.json
  def destroy
    @exploatation.destroy
    respond_to do |format|
      format.html { redirect_to exploatations_url, notice: 'Exploatation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exploatation
      @exploatation = Exploatation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exploatation_params
      params.require(:exploatation).permit(:name, :description, :location, :barcode, :quantity)
    end
end

app/controllers/hardwares_controller.rb
class HardwaresController < ApplicationController
  before_action :set_hardware, only: [:show, :edit, :update, :destroy]

  # GET /hardwares
  # GET /hardwares.json
  def index
    @hardwares = Hardware.all
  end

  # GET /hardwares/1
  # GET /hardwares/1.json
  def show
  end

  # GET /hardwares/new
  def new
    @hardware = Hardware.new
  end

  # GET /hardwares/1/edit
  def edit
  end

  # POST /hardwares
  # POST /hardwares.json
  def create
    @hardware = Hardware.new(hardware_params)

    respond_to do |format|
      if @hardware.save
        format.html { redirect_to @hardware, notice: 'Hardware was successfully created.' }
        format.json { render :show, status: :created, location: @hardware }
      else
        format.html { render :new }
        format.json { render json: @hardware.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hardwares/1
  # PATCH/PUT /hardwares/1.json
  def update
    respond_to do |format|
      if @hardware.update(hardware_params)
        format.html { redirect_to @hardware, notice: 'Hardware was successfully updated.' }
        format.json { render :show, status: :ok, location: @hardware }
      else
        format.html { render :edit }
        format.json { render json: @hardware.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hardwares/1
  # DELETE /hardwares/1.json
  def destroy
    @hardware.destroy
    respond_to do |format|
      format.html { redirect_to hardwares_url, notice: 'Hardware was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hardware
      @hardware = Hardware.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hardware_params
      params.require(:hardware).permit(:name, :description, :sn, :location, :barcode)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exploatations_helper.rb
module ExploatationsHelper
end

app/helpers/hardwares_helper.rb
module HardwaresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/exploatations/_form.html.erb
<%= form_for(@exploatation) do |f| %>
  <% if @exploatation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exploatation.errors.count, "error") %> prohibited this exploatation from being saved:</h2>

      <ul>
      <% @exploatation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :barcode %><br>
    <%= f.text_field :barcode %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exploatations/edit.html.erb
<h1>Editing Exploatation</h1>

<%= render 'form' %>

<%= link_to 'Show', @exploatation %> |
<%= link_to 'Back', exploatations_path %>

app/views/exploatations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Exploatations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Location</th>
      <th>Barcode</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exploatations.each do |exploatation| %>
      <tr>
        <td><%= exploatation.name %></td>
        <td><%= exploatation.description %></td>
        <td><%= exploatation.location %></td>
        <td><%= exploatation.barcode %></td>
        <td><%= exploatation.quantity %></td>
        <td><%= link_to 'Show', exploatation %></td>
        <td><%= link_to 'Edit', edit_exploatation_path(exploatation) %></td>
        <td><%= link_to 'Destroy', exploatation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exploatation', new_exploatation_path %>

app/views/exploatations/new.html.erb
<h1>New Exploatation</h1>

<%= render 'form' %>

<%= link_to 'Back', exploatations_path %>

app/views/exploatations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @exploatation.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @exploatation.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @exploatation.location %>
</p>

<p>
  <strong>Barcode:</strong>
  <%= @exploatation.barcode %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @exploatation.quantity %>
</p>

<%= link_to 'Edit', edit_exploatation_path(@exploatation) %> |
<%= link_to 'Back', exploatations_path %>

app/views/hardwares/_form.html.erb
<%= form_for(@hardware) do |f| %>
  <% if @hardware.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hardware.errors.count, "error") %> prohibited this hardware from being saved:</h2>

      <ul>
      <% @hardware.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :sn %><br>
    <%= f.text_field :sn %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :barcode %><br>
    <%= f.text_field :barcode %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hardwares/edit.html.erb
<h1>Editing Hardware</h1>

<%= render 'form' %>

<%= link_to 'Show', @hardware %> |
<%= link_to 'Back', hardwares_path %>

app/views/hardwares/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista sprzętu</h1>


<%= link_to 'Dodaj nowy', new_hardware_path %><br>
<%= link_to 'Wróć', home_index_path %><br><br>


<table>
  <thead>
    <tr>
      <th>Nazwa</th>
      <th>Opis</th>
      <th>Numer seryjny</th>
      <th>Lokalizacja</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hardwares.each do |hardware| %>
      <tr>
        <td><%= hardware.name %></td>
        <td><%= hardware.description %></td>
        <td><%= hardware.sn %></td>
        <td><%= hardware.location %></td>
        <td><%= link_to 'Pokaż', hardware %></td>
        <td><%= link_to 'Edytuj', edit_hardware_path(hardware) %></td>
        <td><%= link_to 'Usuń', hardware, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/hardwares/new.html.erb
<h1>New Hardware</h1>

<%= render 'form' %>

<%= link_to 'Back', hardwares_path %>

app/views/hardwares/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nazwa:</strong>
  <%= @hardware.name %>
</p>

<p>
  <strong>Opis:</strong>
  <%= @hardware.description %>
</p>

<p>
  <strong>S/N:</strong>
  <%= @hardware.sn %>
</p>

<p>
  <strong>Lokalizacja:</strong>
  <%= @hardware.location %>
</p>

<p>
  <strong>Kod kreskowy:</strong>
  <%= @hardware.barcode %>
</p>

<p>
  <strong>Data utworzenia:</strong>
  <%= @hardware.created_at %>
</p>

<p>
  <strong>Data modyfikacji:</strong>
  <%= @hardware.updated_at %>
</p>

<%= link_to 'Edytuj', edit_hardware_path(@hardware) %> |
<%= link_to 'Wróć', hardwares_path %>

app/views/home/index.html.erb
<h1>Lista działań</h1>


<%= link_to 'Lista Sprzętu', hardwares_path %><br>
<%= link_to 'Lista Eksploatacji', exploatations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Czinv</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>